services:
  - type: web
    name: coppel-motorcycle-checkout
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: "18.18.0"
      - key: NODE_ENV
        value: production
# Nota: Para variables sensibles (API keys, etc.), configúralas en el Dashboard de Render
# como variables de entorno del sitio (se usan en tiempo de build).
